# Generated by Django 5.0.1 on 2024-02-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_donalds', '0003_alter_order_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='staff',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='pickup',
            new_name='take_away',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='_amount',
        ),
        migrations.AddField(
            model_name='productorder',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
